// Preset contents are embedded at build time (see presets-data.ts, generated by
// _gen-presets.cjs) rather than read from disk at request time. Next.js does not
// trace lib/build-mode/presets/* into the route bundle, so a runtime readFileSync
// throws ENOENT (the route's __dirname resolves to a virtual path). Embedding
// makes loadPresets() work identically in the CLI, the dev route, and on Vercel.
import { PRESET_FILES } from "./presets-data";

const MAP: Record<string, string> = {
  "security.md": "docs/context/06-security.md",
  "architecture.md": "docs/context/05-architecture.md",
  "testing.md": "docs/context/testing.md",
  "workflow.md": "docs/context/08-workflow.md",
  "ci.yml": ".github/workflows/ci.yml",
  "dependabot.yml": ".github/dependabot.yml",
  "pre-commit-config.yaml": ".pre-commit-config.yaml",
  "setup.md": "SETUP.md",
  "gitignore": ".gitignore",
};

export function loadPresets(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [src, dest] of Object.entries(MAP)) {
    const content = PRESET_FILES[src];
    if (content === undefined) {
      throw new Error(`missing embedded preset "${src}" — run: node lib/build-mode/_gen-presets.cjs`);
    }
    out[dest] = content;
  }
  return out;
}
